site_name: SafeChord Docs
site_url: https://SafeChord.github.io/Docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.footer
  custom_dir: overrides
  palette:
  - scheme: default
    primary: indigo
    toggle:
      icon: material/weather-night
      name: 切換至深色模式
  - scheme: slate
    primary: indigo
    toggle:
      icon: material/weather-sunny
      name: 切換至淺色模式

nav:
  - 🧩 System Map: safechord.md
  - 🗺️ Knowledge Tree: safechord.knowledgetree.md
  - 🟦 SafeZone (App):
      - Overview: safechord.safezone.md
      - Microservices:
          - Pandemic Simulator: safechord.safezone.service.pandemicsimulator.md
          - Data Ingestor: safechord.safezone.service.dataingestor.md
          - Worker (Golang): safechord.safezone.service.worker.md
          - Analytics API: safechord.safezone.service.analyticsapi.md
          - Dashboard: safechord.safezone.service.dashboard.md
      - Toolkit:
          - CLI (szcli): safechord.safezone.toolkit.cli.md
          - Command Ref: safechord.safezone.toolkit.cli.reference.md
          - Time Server: safechord.safezone.toolkit.timeserver.md
      - Workflow: safechord.safezone.workflow.md
      - ChangeLog: safechord.safezone.changelog.md
  - 🟨 Deployment:
      - Overview: safechord.safezone.deployment.md
      - Helm Architecture: safechord.safezone.deployment.charts.md
      - Workflow: safechord.safezone.deployment.workflow.md
  - 🟥 Chorde (Platform):
      - Overview: safechord.chorde.md
      - K3han Cluster:
          - Overview: safechord.chorde.k3han.md
          - Topology: safechord.chorde.k3han.cluster.md
          - Ingress: safechord.chorde.k3han.ingress.md
          - Scheduling: safechord.chorde.k3han.scheduling.md
          - Monitoring: safechord.chorde.k3han.monitoring.md
          - ChangeLog: safechord.chorde.k3han.changelog.md
  - 🌍 Environment: safechord.environment.md
  - 🛡️ Security: safechord.security.md
  - ⬜ Methodology (KDD):
      - Introduction: safechord.kdd.introduction.md
      - Practice: safechord.kdd.practice.md
      - Workflow: safechord.kdd.workflow.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - tables